### ISSUE TITLE
Prototipo de interfaz

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/practicaprototipos-equipo-f-g-r#2]
--> Link de la interfaz de la aplicación:

https://xd.adobe.com/view/c1f5adcf-95f0-43e6-bc74-8b49c3454f33-94a6/?fullscreen

--> Reporte:

[Reporte de Práctica - Interfaz de Aplicación.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipo-f-g-r/files/6104664/Reporte.de.Practica.-.Interfaz.de.Aplicacion.pdf)

**Comment by Yabin-2021** [comment]
Anexo la Evaluación del Reporte de la Práctica 1.
[Rubrica 1 Practica 1 - Prototipo XD FGR..pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipo-f-g-r/files/6168917/Rubrica.1.Practica.1.-.Prototipo.XD.FGR.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
